complete -c bws -n "__fish_use_subcommand" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_use_subcommand" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_use_subcommand" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_use_subcommand" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_use_subcommand" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_use_subcommand" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_use_subcommand" -s h -l help -d 'Print help'
complete -c bws -n "__fish_use_subcommand" -s V -l version -d 'Print version'
complete -c bws -n "__fish_use_subcommand" -f -a "config"
complete -c bws -n "__fish_use_subcommand" -f -a "completions"
complete -c bws -n "__fish_use_subcommand" -f -a "project"
complete -c bws -n "__fish_use_subcommand" -f -a "secret"
complete -c bws -n "__fish_use_subcommand" -f -a "create"
complete -c bws -n "__fish_use_subcommand" -f -a "delete"
complete -c bws -n "__fish_use_subcommand" -f -a "edit"
complete -c bws -n "__fish_use_subcommand" -f -a "get"
complete -c bws -n "__fish_use_subcommand" -f -a "list"
complete -c bws -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bws -n "__fish_seen_subcommand_from config" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from config" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from config" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from config" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from config" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from config" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from config" -s d -l delete
complete -c bws -n "__fish_seen_subcommand_from config" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c bws -n "__fish_seen_subcommand_from completions" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from completions" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from completions" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from completions" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from completions" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from completions" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from completions" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c bws -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c bws -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "create"
complete -c bws -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "delete"
complete -c bws -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "edit"
complete -c bws -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "get"
complete -c bws -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "list"
complete -c bws -n "__fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from create" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from create" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from create" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from create" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from create" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from create" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from create" -s h -l help -d 'Print help'
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from delete" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from delete" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from delete" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from delete" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from delete" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from delete" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from edit" -l name -r
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from edit" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from edit" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from edit" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from edit" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from edit" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from edit" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from edit" -s h -l help -d 'Print help'
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from get" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from get" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from get" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from get" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from get" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from get" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from get" -s h -l help -d 'Print help'
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from list" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from list" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from list" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from list" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from list" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from list" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "create"
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "delete"
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "edit"
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "get"
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "list"
complete -c bws -n "__fish_seen_subcommand_from project; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bws -n "__fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c bws -n "__fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "create"
complete -c bws -n "__fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "delete"
complete -c bws -n "__fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "edit"
complete -c bws -n "__fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "get"
complete -c bws -n "__fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "list"
complete -c bws -n "__fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from create" -l note -d 'An optional note to add to the secret' -r
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from create" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from create" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from create" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from create" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from create" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from create" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from create" -s h -l help -d 'Print help'
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from delete" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from delete" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from delete" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from delete" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from delete" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from delete" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from delete" -s h -l help -d 'Print help'
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from edit" -l key -r
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from edit" -l value -r
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from edit" -l note -r
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from edit" -l project-id -r
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from edit" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from edit" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from edit" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from edit" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from edit" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from edit" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from edit" -s h -l help -d 'Print help'
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from get" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from get" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from get" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from get" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from get" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from get" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from get" -s h -l help -d 'Print help'
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from list" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from list" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from list" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from list" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from list" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from list" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "create"
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "delete"
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "edit"
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "get"
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "list"
complete -c bws -n "__fish_seen_subcommand_from secret; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bws -n "__fish_seen_subcommand_from create; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from create; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from create; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from create; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from create; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from create; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from create; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c bws -n "__fish_seen_subcommand_from create; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "project"
complete -c bws -n "__fish_seen_subcommand_from create; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "secret"
complete -c bws -n "__fish_seen_subcommand_from create; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bws -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from project" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from project" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from project" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from project" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from project" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from project" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from project" -s h -l help -d 'Print help'
complete -c bws -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from secret" -l note -d 'An optional note to add to the secret' -r
complete -c bws -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from secret" -l project-id -d 'The ID of the project this secret will be added to' -r
complete -c bws -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from secret" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from secret" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from secret" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from secret" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from secret" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from secret" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from secret" -s h -l help -d 'Print help'
complete -c bws -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "project"
complete -c bws -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "secret"
complete -c bws -n "__fish_seen_subcommand_from create; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bws -n "__fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c bws -n "__fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "project"
complete -c bws -n "__fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "secret"
complete -c bws -n "__fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bws -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from project" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from project" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from project" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from project" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from project" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from project" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from project" -s h -l help -d 'Print help'
complete -c bws -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from secret" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from secret" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from secret" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from secret" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from secret" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from secret" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from secret" -s h -l help -d 'Print help'
complete -c bws -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "project"
complete -c bws -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "secret"
complete -c bws -n "__fish_seen_subcommand_from delete; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bws -n "__fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c bws -n "__fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "project"
complete -c bws -n "__fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "secret"
complete -c bws -n "__fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bws -n "__fish_seen_subcommand_from edit; and __fish_seen_subcommand_from project" -l name -r
complete -c bws -n "__fish_seen_subcommand_from edit; and __fish_seen_subcommand_from project" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from edit; and __fish_seen_subcommand_from project" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from edit; and __fish_seen_subcommand_from project" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from edit; and __fish_seen_subcommand_from project" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from edit; and __fish_seen_subcommand_from project" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from edit; and __fish_seen_subcommand_from project" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from edit; and __fish_seen_subcommand_from project" -s h -l help -d 'Print help'
complete -c bws -n "__fish_seen_subcommand_from edit; and __fish_seen_subcommand_from secret" -l key -r
complete -c bws -n "__fish_seen_subcommand_from edit; and __fish_seen_subcommand_from secret" -l value -r
complete -c bws -n "__fish_seen_subcommand_from edit; and __fish_seen_subcommand_from secret" -l note -r
complete -c bws -n "__fish_seen_subcommand_from edit; and __fish_seen_subcommand_from secret" -l project-id -r
complete -c bws -n "__fish_seen_subcommand_from edit; and __fish_seen_subcommand_from secret" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from edit; and __fish_seen_subcommand_from secret" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from edit; and __fish_seen_subcommand_from secret" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from edit; and __fish_seen_subcommand_from secret" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from edit; and __fish_seen_subcommand_from secret" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from edit; and __fish_seen_subcommand_from secret" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from edit; and __fish_seen_subcommand_from secret" -s h -l help -d 'Print help'
complete -c bws -n "__fish_seen_subcommand_from edit; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "project"
complete -c bws -n "__fish_seen_subcommand_from edit; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "secret"
complete -c bws -n "__fish_seen_subcommand_from edit; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bws -n "__fish_seen_subcommand_from get; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from get; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from get; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from get; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from get; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from get; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from get; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c bws -n "__fish_seen_subcommand_from get; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "project"
complete -c bws -n "__fish_seen_subcommand_from get; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "secret"
complete -c bws -n "__fish_seen_subcommand_from get; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bws -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from project" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from project" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from project" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from project" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from project" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from project" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from project" -s h -l help -d 'Print help'
complete -c bws -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from secret" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from secret" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from secret" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from secret" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from secret" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from secret" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from secret" -s h -l help -d 'Print help'
complete -c bws -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "project"
complete -c bws -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "secret"
complete -c bws -n "__fish_seen_subcommand_from get; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bws -n "__fish_seen_subcommand_from list; and not __fish_seen_subcommand_from projects; and not __fish_seen_subcommand_from secrets; and not __fish_seen_subcommand_from help" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from list; and not __fish_seen_subcommand_from projects; and not __fish_seen_subcommand_from secrets; and not __fish_seen_subcommand_from help" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from list; and not __fish_seen_subcommand_from projects; and not __fish_seen_subcommand_from secrets; and not __fish_seen_subcommand_from help" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from list; and not __fish_seen_subcommand_from projects; and not __fish_seen_subcommand_from secrets; and not __fish_seen_subcommand_from help" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from list; and not __fish_seen_subcommand_from projects; and not __fish_seen_subcommand_from secrets; and not __fish_seen_subcommand_from help" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from list; and not __fish_seen_subcommand_from projects; and not __fish_seen_subcommand_from secrets; and not __fish_seen_subcommand_from help" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from list; and not __fish_seen_subcommand_from projects; and not __fish_seen_subcommand_from secrets; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c bws -n "__fish_seen_subcommand_from list; and not __fish_seen_subcommand_from projects; and not __fish_seen_subcommand_from secrets; and not __fish_seen_subcommand_from help" -f -a "projects"
complete -c bws -n "__fish_seen_subcommand_from list; and not __fish_seen_subcommand_from projects; and not __fish_seen_subcommand_from secrets; and not __fish_seen_subcommand_from help" -f -a "secrets"
complete -c bws -n "__fish_seen_subcommand_from list; and not __fish_seen_subcommand_from projects; and not __fish_seen_subcommand_from secrets; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bws -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from projects" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from projects" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from projects" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from projects" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from projects" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from projects" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from projects" -s h -l help -d 'Print help'
complete -c bws -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from secrets" -s o -l output -d 'Output format' -r -f -a "{json	'',yaml	'',env	'',table	'',tsv	'',none	''}"
complete -c bws -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from secrets" -s c -l color -d 'Use colors in the output' -r -f -a "{no	'',yes	'',auto	''}"
complete -c bws -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from secrets" -s t -l access-token -d 'Specify access token for the machine account' -r
complete -c bws -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from secrets" -s f -l config-file -d '[default: ~/.bws/config] Config file to use' -r -F
complete -c bws -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from secrets" -s p -l profile -d 'Profile to use from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from secrets" -s u -l server-url -d 'Override the server URL from the config file' -r
complete -c bws -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from secrets" -s h -l help -d 'Print help'
complete -c bws -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from projects; and not __fish_seen_subcommand_from secrets; and not __fish_seen_subcommand_from help" -f -a "projects"
complete -c bws -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from projects; and not __fish_seen_subcommand_from secrets; and not __fish_seen_subcommand_from help" -f -a "secrets"
complete -c bws -n "__fish_seen_subcommand_from list; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from projects; and not __fish_seen_subcommand_from secrets; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bws -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "config"
complete -c bws -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "completions"
complete -c bws -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "project"
complete -c bws -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "secret"
complete -c bws -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "create"
complete -c bws -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "delete"
complete -c bws -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "edit"
complete -c bws -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "get"
complete -c bws -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "list"
complete -c bws -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c bws -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list" -f -a "create"
complete -c bws -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list" -f -a "delete"
complete -c bws -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list" -f -a "edit"
complete -c bws -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list" -f -a "get"
complete -c bws -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list" -f -a "list"
complete -c bws -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list" -f -a "create"
complete -c bws -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list" -f -a "delete"
complete -c bws -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list" -f -a "edit"
complete -c bws -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list" -f -a "get"
complete -c bws -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from secret; and not __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from list" -f -a "list"
complete -c bws -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret" -f -a "project"
complete -c bws -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from create; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret" -f -a "secret"
complete -c bws -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret" -f -a "project"
complete -c bws -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from delete; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret" -f -a "secret"
complete -c bws -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret" -f -a "project"
complete -c bws -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from edit; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret" -f -a "secret"
complete -c bws -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret" -f -a "project"
complete -c bws -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from get; and not __fish_seen_subcommand_from project; and not __fish_seen_subcommand_from secret" -f -a "secret"
complete -c bws -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from projects; and not __fish_seen_subcommand_from secrets" -f -a "projects"
complete -c bws -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from list; and not __fish_seen_subcommand_from projects; and not __fish_seen_subcommand_from secrets" -f -a "secrets"
