complete -c dprint -n "__fish_use_subcommand" -s c -l config -d 'Path or url to JSON configuration file. Defaults to dprint.json(c) or .dprint.json(c) in current or ancestor directory when not provided.' -r
complete -c dprint -n "__fish_use_subcommand" -l plugins -d 'List of urls or file paths of plugins to use. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_use_subcommand" -s L -l log-level -d 'Set log level' -r -f -a "{debug	'',info	'',warn	'',error	'',silent	''}"
complete -c dprint -n "__fish_use_subcommand" -l verbose -d 'Alias for --log-level=debug'
complete -c dprint -n "__fish_use_subcommand" -s h -l help -d 'Print help'
complete -c dprint -n "__fish_use_subcommand" -s V -l version -d 'Print version'
complete -c dprint -n "__fish_use_subcommand" -f -a "init" -d 'Initializes a configuration file in the current directory.'
complete -c dprint -n "__fish_use_subcommand" -f -a "fmt" -d 'Formats the source files and writes the result to the file system.'
complete -c dprint -n "__fish_use_subcommand" -f -a "check" -d 'Checks for any files that haven\'t been formatted.'
complete -c dprint -n "__fish_use_subcommand" -f -a "config" -d 'Functionality related to the configuration file.'
complete -c dprint -n "__fish_use_subcommand" -f -a "output-file-paths" -d 'Prints the resolved file paths for the plugins based on the args and configuration.'
complete -c dprint -n "__fish_use_subcommand" -f -a "output-resolved-config" -d 'Prints the resolved configuration for the plugins based on the args and configuration.'
complete -c dprint -n "__fish_use_subcommand" -f -a "output-format-times" -d 'Prints the amount of time it takes to format each file. Use this for debugging.'
complete -c dprint -n "__fish_use_subcommand" -f -a "clear-cache" -d 'Deletes the plugin cache directory.'
complete -c dprint -n "__fish_use_subcommand" -f -a "upgrade" -d 'Upgrades the dprint executable.'
complete -c dprint -n "__fish_use_subcommand" -f -a "completions" -d 'Generate shell completions script for dprint'
complete -c dprint -n "__fish_use_subcommand" -f -a "license" -d 'Outputs the software license.'
complete -c dprint -n "__fish_use_subcommand" -f -a "editor-info"
complete -c dprint -n "__fish_use_subcommand" -f -a "editor-service"
complete -c dprint -n "__fish_use_subcommand" -f -a "lsp" -d 'Starts up a language server for formatting files.'
complete -c dprint -n "__fish_use_subcommand" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c dprint -n "__fish_seen_subcommand_from init" -s c -l config -d 'Path or url to JSON configuration file. Defaults to dprint.json(c) or .dprint.json(c) in current or ancestor directory when not provided.' -r
complete -c dprint -n "__fish_seen_subcommand_from init" -l plugins -d 'List of urls or file paths of plugins to use. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from init" -s L -l log-level -d 'Set log level' -r -f -a "{debug	'',info	'',warn	'',error	'',silent	''}"
complete -c dprint -n "__fish_seen_subcommand_from init" -l verbose -d 'Alias for --log-level=debug'
complete -c dprint -n "__fish_seen_subcommand_from init" -s h -l help -d 'Print help'
complete -c dprint -n "__fish_seen_subcommand_from fmt" -l includes-override -d 'List of file patterns in quotes to format. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from fmt" -l excludes -d 'List of file patterns or directories in quotes to exclude when formatting. This excludes in addition to what is found in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from fmt" -l excludes-override -d 'List of file patterns or directories in quotes to exclude when formatting. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from fmt" -l incremental -d 'Only format files when they change. This may alternatively be specified in the configuration file.' -r -f -a "{true	'',false	''}"
complete -c dprint -n "__fish_seen_subcommand_from fmt" -l stdin -d 'Format stdin and output the result to stdout. Provide an absolute file path to apply the inclusion and exclusion rules or an extension or file name to always format the text.' -r
complete -c dprint -n "__fish_seen_subcommand_from fmt" -s c -l config -d 'Path or url to JSON configuration file. Defaults to dprint.json(c) or .dprint.json(c) in current or ancestor directory when not provided.' -r
complete -c dprint -n "__fish_seen_subcommand_from fmt" -l plugins -d 'List of urls or file paths of plugins to use. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from fmt" -s L -l log-level -d 'Set log level' -r -f -a "{debug	'',info	'',warn	'',error	'',silent	''}"
complete -c dprint -n "__fish_seen_subcommand_from fmt" -l allow-node-modules -d 'Allows traversing node module directories (unstable - This flag will be renamed to be non-node specific in the future).'
complete -c dprint -n "__fish_seen_subcommand_from fmt" -l diff -d 'Outputs a check-like diff of every formatted file.'
complete -c dprint -n "__fish_seen_subcommand_from fmt" -l staged -d 'Format only the staged files.'
complete -c dprint -n "__fish_seen_subcommand_from fmt" -l allow-no-files -d 'Causes dprint to exit with exit code 0 when no files are found instead of exit code 14.'
complete -c dprint -n "__fish_seen_subcommand_from fmt" -l skip-stable-format -d 'Whether to skip formatting a file multiple times until the output is stable'
complete -c dprint -n "__fish_seen_subcommand_from fmt" -l verbose -d 'Alias for --log-level=debug'
complete -c dprint -n "__fish_seen_subcommand_from fmt" -s h -l help -d 'Print help'
complete -c dprint -n "__fish_seen_subcommand_from check" -l includes-override -d 'List of file patterns in quotes to format. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from check" -l excludes -d 'List of file patterns or directories in quotes to exclude when formatting. This excludes in addition to what is found in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from check" -l excludes-override -d 'List of file patterns or directories in quotes to exclude when formatting. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from check" -l incremental -d 'Only format files when they change. This may alternatively be specified in the configuration file.' -r -f -a "{true	'',false	''}"
complete -c dprint -n "__fish_seen_subcommand_from check" -s c -l config -d 'Path or url to JSON configuration file. Defaults to dprint.json(c) or .dprint.json(c) in current or ancestor directory when not provided.' -r
complete -c dprint -n "__fish_seen_subcommand_from check" -l plugins -d 'List of urls or file paths of plugins to use. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from check" -s L -l log-level -d 'Set log level' -r -f -a "{debug	'',info	'',warn	'',error	'',silent	''}"
complete -c dprint -n "__fish_seen_subcommand_from check" -l allow-node-modules -d 'Allows traversing node module directories (unstable - This flag will be renamed to be non-node specific in the future).'
complete -c dprint -n "__fish_seen_subcommand_from check" -l allow-no-files -d 'Causes dprint to exit with exit code 0 when no files are found instead of exit code 14.'
complete -c dprint -n "__fish_seen_subcommand_from check" -l staged -d 'Format only the staged files.'
complete -c dprint -n "__fish_seen_subcommand_from check" -l list-different -d 'Only outputs file paths that aren\'t formatted and doesn\'t output diffs.'
complete -c dprint -n "__fish_seen_subcommand_from check" -l verbose -d 'Alias for --log-level=debug'
complete -c dprint -n "__fish_seen_subcommand_from check" -s h -l help -d 'Print help'
complete -c dprint -n "__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from update; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from help" -s c -l config -d 'Path or url to JSON configuration file. Defaults to dprint.json(c) or .dprint.json(c) in current or ancestor directory when not provided.' -r
complete -c dprint -n "__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from update; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from help" -l plugins -d 'List of urls or file paths of plugins to use. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from update; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from help" -s L -l log-level -d 'Set log level' -r -f -a "{debug	'',info	'',warn	'',error	'',silent	''}"
complete -c dprint -n "__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from update; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from help" -l verbose -d 'Alias for --log-level=debug'
complete -c dprint -n "__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from update; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from help" -s h -l help -d 'Print help'
complete -c dprint -n "__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from update; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from help" -f -a "init" -d 'Initializes a configuration file in the current directory.'
complete -c dprint -n "__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from update; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from help" -f -a "update" -d 'Updates the plugins in the configuration file.'
complete -c dprint -n "__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from update; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from help" -f -a "add" -d 'Adds a plugin to the configuration file.'
complete -c dprint -n "__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from update; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c dprint -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from init" -s c -l config -d 'Path or url to JSON configuration file. Defaults to dprint.json(c) or .dprint.json(c) in current or ancestor directory when not provided.' -r
complete -c dprint -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from init" -l plugins -d 'List of urls or file paths of plugins to use. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from init" -s L -l log-level -d 'Set log level' -r -f -a "{debug	'',info	'',warn	'',error	'',silent	''}"
complete -c dprint -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from init" -l verbose -d 'Alias for --log-level=debug'
complete -c dprint -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from init" -s h -l help -d 'Print help'
complete -c dprint -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from update" -s c -l config -d 'Path or url to JSON configuration file. Defaults to dprint.json(c) or .dprint.json(c) in current or ancestor directory when not provided.' -r
complete -c dprint -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from update" -l plugins -d 'List of urls or file paths of plugins to use. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from update" -s L -l log-level -d 'Set log level' -r -f -a "{debug	'',info	'',warn	'',error	'',silent	''}"
complete -c dprint -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from update" -s y -l yes -d 'Upgrade process plugins without prompting to confirm checksums.'
complete -c dprint -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from update" -l verbose -d 'Alias for --log-level=debug'
complete -c dprint -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from update" -s h -l help -d 'Print help'
complete -c dprint -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from add" -s c -l config -d 'Path or url to JSON configuration file. Defaults to dprint.json(c) or .dprint.json(c) in current or ancestor directory when not provided.' -r
complete -c dprint -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from add" -l plugins -d 'List of urls or file paths of plugins to use. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from add" -s L -l log-level -d 'Set log level' -r -f -a "{debug	'',info	'',warn	'',error	'',silent	''}"
complete -c dprint -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from add" -l verbose -d 'Alias for --log-level=debug'
complete -c dprint -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from add" -s h -l help -d 'Print help'
complete -c dprint -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from update; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from help" -f -a "init" -d 'Initializes a configuration file in the current directory.'
complete -c dprint -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from update; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from help" -f -a "update" -d 'Updates the plugins in the configuration file.'
complete -c dprint -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from update; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from help" -f -a "add" -d 'Adds a plugin to the configuration file.'
complete -c dprint -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from update; and not __fish_seen_subcommand_from add; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c dprint -n "__fish_seen_subcommand_from output-file-paths" -l includes-override -d 'List of file patterns in quotes to format. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from output-file-paths" -l excludes -d 'List of file patterns or directories in quotes to exclude when formatting. This excludes in addition to what is found in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from output-file-paths" -l excludes-override -d 'List of file patterns or directories in quotes to exclude when formatting. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from output-file-paths" -s c -l config -d 'Path or url to JSON configuration file. Defaults to dprint.json(c) or .dprint.json(c) in current or ancestor directory when not provided.' -r
complete -c dprint -n "__fish_seen_subcommand_from output-file-paths" -l plugins -d 'List of urls or file paths of plugins to use. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from output-file-paths" -s L -l log-level -d 'Set log level' -r -f -a "{debug	'',info	'',warn	'',error	'',silent	''}"
complete -c dprint -n "__fish_seen_subcommand_from output-file-paths" -l allow-node-modules -d 'Allows traversing node module directories (unstable - This flag will be renamed to be non-node specific in the future).'
complete -c dprint -n "__fish_seen_subcommand_from output-file-paths" -l staged -d 'Format only the staged files.'
complete -c dprint -n "__fish_seen_subcommand_from output-file-paths" -l verbose -d 'Alias for --log-level=debug'
complete -c dprint -n "__fish_seen_subcommand_from output-file-paths" -s h -l help -d 'Print help'
complete -c dprint -n "__fish_seen_subcommand_from output-resolved-config" -s c -l config -d 'Path or url to JSON configuration file. Defaults to dprint.json(c) or .dprint.json(c) in current or ancestor directory when not provided.' -r
complete -c dprint -n "__fish_seen_subcommand_from output-resolved-config" -l plugins -d 'List of urls or file paths of plugins to use. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from output-resolved-config" -s L -l log-level -d 'Set log level' -r -f -a "{debug	'',info	'',warn	'',error	'',silent	''}"
complete -c dprint -n "__fish_seen_subcommand_from output-resolved-config" -l verbose -d 'Alias for --log-level=debug'
complete -c dprint -n "__fish_seen_subcommand_from output-resolved-config" -s h -l help -d 'Print help'
complete -c dprint -n "__fish_seen_subcommand_from output-format-times" -l includes-override -d 'List of file patterns in quotes to format. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from output-format-times" -l excludes -d 'List of file patterns or directories in quotes to exclude when formatting. This excludes in addition to what is found in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from output-format-times" -l excludes-override -d 'List of file patterns or directories in quotes to exclude when formatting. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from output-format-times" -s c -l config -d 'Path or url to JSON configuration file. Defaults to dprint.json(c) or .dprint.json(c) in current or ancestor directory when not provided.' -r
complete -c dprint -n "__fish_seen_subcommand_from output-format-times" -l plugins -d 'List of urls or file paths of plugins to use. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from output-format-times" -s L -l log-level -d 'Set log level' -r -f -a "{debug	'',info	'',warn	'',error	'',silent	''}"
complete -c dprint -n "__fish_seen_subcommand_from output-format-times" -l allow-node-modules -d 'Allows traversing node module directories (unstable - This flag will be renamed to be non-node specific in the future).'
complete -c dprint -n "__fish_seen_subcommand_from output-format-times" -l allow-no-files -d 'Causes dprint to exit with exit code 0 when no files are found instead of exit code 14.'
complete -c dprint -n "__fish_seen_subcommand_from output-format-times" -l staged -d 'Format only the staged files.'
complete -c dprint -n "__fish_seen_subcommand_from output-format-times" -l verbose -d 'Alias for --log-level=debug'
complete -c dprint -n "__fish_seen_subcommand_from output-format-times" -s h -l help -d 'Print help'
complete -c dprint -n "__fish_seen_subcommand_from clear-cache" -s c -l config -d 'Path or url to JSON configuration file. Defaults to dprint.json(c) or .dprint.json(c) in current or ancestor directory when not provided.' -r
complete -c dprint -n "__fish_seen_subcommand_from clear-cache" -l plugins -d 'List of urls or file paths of plugins to use. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from clear-cache" -s L -l log-level -d 'Set log level' -r -f -a "{debug	'',info	'',warn	'',error	'',silent	''}"
complete -c dprint -n "__fish_seen_subcommand_from clear-cache" -l verbose -d 'Alias for --log-level=debug'
complete -c dprint -n "__fish_seen_subcommand_from clear-cache" -s h -l help -d 'Print help'
complete -c dprint -n "__fish_seen_subcommand_from upgrade" -s c -l config -d 'Path or url to JSON configuration file. Defaults to dprint.json(c) or .dprint.json(c) in current or ancestor directory when not provided.' -r
complete -c dprint -n "__fish_seen_subcommand_from upgrade" -l plugins -d 'List of urls or file paths of plugins to use. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from upgrade" -s L -l log-level -d 'Set log level' -r -f -a "{debug	'',info	'',warn	'',error	'',silent	''}"
complete -c dprint -n "__fish_seen_subcommand_from upgrade" -l verbose -d 'Alias for --log-level=debug'
complete -c dprint -n "__fish_seen_subcommand_from upgrade" -s h -l help -d 'Print help'
complete -c dprint -n "__fish_seen_subcommand_from completions" -s c -l config -d 'Path or url to JSON configuration file. Defaults to dprint.json(c) or .dprint.json(c) in current or ancestor directory when not provided.' -r
complete -c dprint -n "__fish_seen_subcommand_from completions" -l plugins -d 'List of urls or file paths of plugins to use. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from completions" -s L -l log-level -d 'Set log level' -r -f -a "{debug	'',info	'',warn	'',error	'',silent	''}"
complete -c dprint -n "__fish_seen_subcommand_from completions" -l verbose -d 'Alias for --log-level=debug'
complete -c dprint -n "__fish_seen_subcommand_from completions" -s h -l help -d 'Print help'
complete -c dprint -n "__fish_seen_subcommand_from license" -s c -l config -d 'Path or url to JSON configuration file. Defaults to dprint.json(c) or .dprint.json(c) in current or ancestor directory when not provided.' -r
complete -c dprint -n "__fish_seen_subcommand_from license" -l plugins -d 'List of urls or file paths of plugins to use. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from license" -s L -l log-level -d 'Set log level' -r -f -a "{debug	'',info	'',warn	'',error	'',silent	''}"
complete -c dprint -n "__fish_seen_subcommand_from license" -l verbose -d 'Alias for --log-level=debug'
complete -c dprint -n "__fish_seen_subcommand_from license" -s h -l help -d 'Print help'
complete -c dprint -n "__fish_seen_subcommand_from editor-info" -s c -l config -d 'Path or url to JSON configuration file. Defaults to dprint.json(c) or .dprint.json(c) in current or ancestor directory when not provided.' -r
complete -c dprint -n "__fish_seen_subcommand_from editor-info" -l plugins -d 'List of urls or file paths of plugins to use. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from editor-info" -s L -l log-level -d 'Set log level' -r -f -a "{debug	'',info	'',warn	'',error	'',silent	''}"
complete -c dprint -n "__fish_seen_subcommand_from editor-info" -l verbose -d 'Alias for --log-level=debug'
complete -c dprint -n "__fish_seen_subcommand_from editor-info" -s h -l help -d 'Print help'
complete -c dprint -n "__fish_seen_subcommand_from editor-service" -l parent-pid -r
complete -c dprint -n "__fish_seen_subcommand_from editor-service" -s c -l config -d 'Path or url to JSON configuration file. Defaults to dprint.json(c) or .dprint.json(c) in current or ancestor directory when not provided.' -r
complete -c dprint -n "__fish_seen_subcommand_from editor-service" -l plugins -d 'List of urls or file paths of plugins to use. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from editor-service" -s L -l log-level -d 'Set log level' -r -f -a "{debug	'',info	'',warn	'',error	'',silent	''}"
complete -c dprint -n "__fish_seen_subcommand_from editor-service" -l verbose -d 'Alias for --log-level=debug'
complete -c dprint -n "__fish_seen_subcommand_from editor-service" -s h -l help -d 'Print help'
complete -c dprint -n "__fish_seen_subcommand_from lsp" -s c -l config -d 'Path or url to JSON configuration file. Defaults to dprint.json(c) or .dprint.json(c) in current or ancestor directory when not provided.' -r
complete -c dprint -n "__fish_seen_subcommand_from lsp" -l plugins -d 'List of urls or file paths of plugins to use. This overrides what is specified in the config file.' -r
complete -c dprint -n "__fish_seen_subcommand_from lsp" -s L -l log-level -d 'Set log level' -r -f -a "{debug	'',info	'',warn	'',error	'',silent	''}"
complete -c dprint -n "__fish_seen_subcommand_from lsp" -l verbose -d 'Alias for --log-level=debug'
complete -c dprint -n "__fish_seen_subcommand_from lsp" -s h -l help -d 'Print help'
complete -c dprint -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from fmt; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from output-file-paths; and not __fish_seen_subcommand_from output-resolved-config; and not __fish_seen_subcommand_from output-format-times; and not __fish_seen_subcommand_from clear-cache; and not __fish_seen_subcommand_from upgrade; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from license; and not __fish_seen_subcommand_from editor-info; and not __fish_seen_subcommand_from editor-service; and not __fish_seen_subcommand_from lsp; and not __fish_seen_subcommand_from help" -f -a "init" -d 'Initializes a configuration file in the current directory.'
complete -c dprint -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from fmt; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from output-file-paths; and not __fish_seen_subcommand_from output-resolved-config; and not __fish_seen_subcommand_from output-format-times; and not __fish_seen_subcommand_from clear-cache; and not __fish_seen_subcommand_from upgrade; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from license; and not __fish_seen_subcommand_from editor-info; and not __fish_seen_subcommand_from editor-service; and not __fish_seen_subcommand_from lsp; and not __fish_seen_subcommand_from help" -f -a "fmt" -d 'Formats the source files and writes the result to the file system.'
complete -c dprint -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from fmt; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from output-file-paths; and not __fish_seen_subcommand_from output-resolved-config; and not __fish_seen_subcommand_from output-format-times; and not __fish_seen_subcommand_from clear-cache; and not __fish_seen_subcommand_from upgrade; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from license; and not __fish_seen_subcommand_from editor-info; and not __fish_seen_subcommand_from editor-service; and not __fish_seen_subcommand_from lsp; and not __fish_seen_subcommand_from help" -f -a "check" -d 'Checks for any files that haven\'t been formatted.'
complete -c dprint -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from fmt; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from output-file-paths; and not __fish_seen_subcommand_from output-resolved-config; and not __fish_seen_subcommand_from output-format-times; and not __fish_seen_subcommand_from clear-cache; and not __fish_seen_subcommand_from upgrade; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from license; and not __fish_seen_subcommand_from editor-info; and not __fish_seen_subcommand_from editor-service; and not __fish_seen_subcommand_from lsp; and not __fish_seen_subcommand_from help" -f -a "config" -d 'Functionality related to the configuration file.'
complete -c dprint -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from fmt; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from output-file-paths; and not __fish_seen_subcommand_from output-resolved-config; and not __fish_seen_subcommand_from output-format-times; and not __fish_seen_subcommand_from clear-cache; and not __fish_seen_subcommand_from upgrade; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from license; and not __fish_seen_subcommand_from editor-info; and not __fish_seen_subcommand_from editor-service; and not __fish_seen_subcommand_from lsp; and not __fish_seen_subcommand_from help" -f -a "output-file-paths" -d 'Prints the resolved file paths for the plugins based on the args and configuration.'
complete -c dprint -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from fmt; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from output-file-paths; and not __fish_seen_subcommand_from output-resolved-config; and not __fish_seen_subcommand_from output-format-times; and not __fish_seen_subcommand_from clear-cache; and not __fish_seen_subcommand_from upgrade; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from license; and not __fish_seen_subcommand_from editor-info; and not __fish_seen_subcommand_from editor-service; and not __fish_seen_subcommand_from lsp; and not __fish_seen_subcommand_from help" -f -a "output-resolved-config" -d 'Prints the resolved configuration for the plugins based on the args and configuration.'
complete -c dprint -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from fmt; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from output-file-paths; and not __fish_seen_subcommand_from output-resolved-config; and not __fish_seen_subcommand_from output-format-times; and not __fish_seen_subcommand_from clear-cache; and not __fish_seen_subcommand_from upgrade; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from license; and not __fish_seen_subcommand_from editor-info; and not __fish_seen_subcommand_from editor-service; and not __fish_seen_subcommand_from lsp; and not __fish_seen_subcommand_from help" -f -a "output-format-times" -d 'Prints the amount of time it takes to format each file. Use this for debugging.'
complete -c dprint -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from fmt; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from output-file-paths; and not __fish_seen_subcommand_from output-resolved-config; and not __fish_seen_subcommand_from output-format-times; and not __fish_seen_subcommand_from clear-cache; and not __fish_seen_subcommand_from upgrade; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from license; and not __fish_seen_subcommand_from editor-info; and not __fish_seen_subcommand_from editor-service; and not __fish_seen_subcommand_from lsp; and not __fish_seen_subcommand_from help" -f -a "clear-cache" -d 'Deletes the plugin cache directory.'
complete -c dprint -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from fmt; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from output-file-paths; and not __fish_seen_subcommand_from output-resolved-config; and not __fish_seen_subcommand_from output-format-times; and not __fish_seen_subcommand_from clear-cache; and not __fish_seen_subcommand_from upgrade; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from license; and not __fish_seen_subcommand_from editor-info; and not __fish_seen_subcommand_from editor-service; and not __fish_seen_subcommand_from lsp; and not __fish_seen_subcommand_from help" -f -a "upgrade" -d 'Upgrades the dprint executable.'
complete -c dprint -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from fmt; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from output-file-paths; and not __fish_seen_subcommand_from output-resolved-config; and not __fish_seen_subcommand_from output-format-times; and not __fish_seen_subcommand_from clear-cache; and not __fish_seen_subcommand_from upgrade; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from license; and not __fish_seen_subcommand_from editor-info; and not __fish_seen_subcommand_from editor-service; and not __fish_seen_subcommand_from lsp; and not __fish_seen_subcommand_from help" -f -a "completions" -d 'Generate shell completions script for dprint'
complete -c dprint -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from fmt; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from output-file-paths; and not __fish_seen_subcommand_from output-resolved-config; and not __fish_seen_subcommand_from output-format-times; and not __fish_seen_subcommand_from clear-cache; and not __fish_seen_subcommand_from upgrade; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from license; and not __fish_seen_subcommand_from editor-info; and not __fish_seen_subcommand_from editor-service; and not __fish_seen_subcommand_from lsp; and not __fish_seen_subcommand_from help" -f -a "license" -d 'Outputs the software license.'
complete -c dprint -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from fmt; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from output-file-paths; and not __fish_seen_subcommand_from output-resolved-config; and not __fish_seen_subcommand_from output-format-times; and not __fish_seen_subcommand_from clear-cache; and not __fish_seen_subcommand_from upgrade; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from license; and not __fish_seen_subcommand_from editor-info; and not __fish_seen_subcommand_from editor-service; and not __fish_seen_subcommand_from lsp; and not __fish_seen_subcommand_from help" -f -a "editor-info"
complete -c dprint -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from fmt; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from output-file-paths; and not __fish_seen_subcommand_from output-resolved-config; and not __fish_seen_subcommand_from output-format-times; and not __fish_seen_subcommand_from clear-cache; and not __fish_seen_subcommand_from upgrade; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from license; and not __fish_seen_subcommand_from editor-info; and not __fish_seen_subcommand_from editor-service; and not __fish_seen_subcommand_from lsp; and not __fish_seen_subcommand_from help" -f -a "editor-service"
complete -c dprint -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from fmt; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from output-file-paths; and not __fish_seen_subcommand_from output-resolved-config; and not __fish_seen_subcommand_from output-format-times; and not __fish_seen_subcommand_from clear-cache; and not __fish_seen_subcommand_from upgrade; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from license; and not __fish_seen_subcommand_from editor-info; and not __fish_seen_subcommand_from editor-service; and not __fish_seen_subcommand_from lsp; and not __fish_seen_subcommand_from help" -f -a "lsp" -d 'Starts up a language server for formatting files.'
complete -c dprint -n "__fish_seen_subcommand_from help; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from fmt; and not __fish_seen_subcommand_from check; and not __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from output-file-paths; and not __fish_seen_subcommand_from output-resolved-config; and not __fish_seen_subcommand_from output-format-times; and not __fish_seen_subcommand_from clear-cache; and not __fish_seen_subcommand_from upgrade; and not __fish_seen_subcommand_from completions; and not __fish_seen_subcommand_from license; and not __fish_seen_subcommand_from editor-info; and not __fish_seen_subcommand_from editor-service; and not __fish_seen_subcommand_from lsp; and not __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c dprint -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from update; and not __fish_seen_subcommand_from add" -f -a "init" -d 'Initializes a configuration file in the current directory.'
complete -c dprint -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from update; and not __fish_seen_subcommand_from add" -f -a "update" -d 'Updates the plugins in the configuration file.'
complete -c dprint -n "__fish_seen_subcommand_from help; and __fish_seen_subcommand_from config; and not __fish_seen_subcommand_from init; and not __fish_seen_subcommand_from update; and not __fish_seen_subcommand_from add" -f -a "add" -d 'Adds a plugin to the configuration file.'
