# Fonts
font_family Hasklug Nerd Font Mono Medium
bold_font Hasklug Nerd Font Mono SemiBold
bold_italic_font Hasklug Nerd Font Mono SemiBold Italic
italic_font Cartograph CF Italic
font_size 14
modify_font cell_height 125%
modify_font cell_width 95%
modify_font underline_position 4
modify_font underline_thickness 150%
text_composition_strategy legacy

# Some symbols that break in italic.
symbol_map Uf487 Hasklug Nerd Font Mono Medium

# Cursor
cursor_blink_interval 0

# Mouse
mouse_hide_wait 10.0
url_style double

# Shhhhh
enable_audio_bell no

# Tab bar
tab_bar_edge top
tab_bar_margin_width 5
tab_bar_margin_height 5 0
tab_bar_style separator
tab_bar_min_tabs 2
tab_separator ""
tab_title_template "{fmt.fg._5c6370}{fmt.bg.default}{fmt.fg._abb2bf}{fmt.bg._5c6370} {tab.active_oldest_wd} {fmt.fg._5c6370}{fmt.bg.default} "
active_tab_title_template "{fmt.fg._BAA0E8}{fmt.bg.default}{fmt.fg.default}{fmt.bg._BAA0E8} {tab.active_oldest_wd} {fmt.fg._BAA0E8}{fmt.bg.default} "

# OS stuff
macos_option_as_alt yes
macos_quit_when_last_window_closed yes

# Open the scrollback buffer in Neovim.
map kitty_mod+h launch --stdin-source=@screen_scrollback --stdin-add-formatting --type=overlay --env=SCROLLBACK_PAGE=1 nvim -R -M -

# Keyboard shortcuts
kitty_mod cmd+shift
map cmd+s send_text all \x13
map cmd+t new_tab_with_cwd
map kitty_mod+enter launch --cwd=current

# Move between tabs
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7

# Layout movement and settings.
enabled_layouts Splits,fat:bias=70
map kitty_mod+up neighboring_window up
map kitty_mod+down neighboring_window down
map kitty_mod+left neighboring_window left
map kitty_mod+right neighboring_window right
map kitty_mod+s launch --location=hsplit
map kitty_mod+v launch --location=vsplit
map ctrl+` close_window

# Color theme.
include theme.conf
