# vim:fileencoding=utf-8:foldmethod=marker

# Fonts
font_family Macon Book
italic_font Macon RegularItalic
font_size 14.0
modify_font cell_width 95%
modify_font underline_position 4
text_composition_strategy legacy
symbol_map U+002D,U+00AD,U+2212 Macon Book

# Cursor
cursor #9FE3F2
cursor_text_color #000000
cursor_shape block
cursor_blink_interval 0

# Mouse
mouse_hide_wait 10.0
url_style double

# Tab bar
tab_bar_edge top
tab_bar_margin_width 5
tab_bar_margin_height 5 0
tab_bar_style separator
tab_bar_min_tabs 2
tab_separator ""
tab_title_template "{fmt.fg._5c6370}{fmt.bg.default}{fmt.fg._abb2bf}{fmt.bg._5c6370} {title.split()[0]} {fmt.fg._5c6370}{fmt.bg.default} "
active_tab_title_template "{fmt.fg._BAA0E8}{fmt.bg.default}{fmt.fg.default}{fmt.bg._BAA0E8} {title.split()[0]} {fmt.fg._BAA0E8}{fmt.bg.default} "

# OS stuff
macos_option_as_alt yes
editor /opt/homebrew/bin/nvim

# Keyboard shortcuts
kitty_mod cmd+shift
map cmd+s send_text all \x13
map cmd+h send_text all \x08
map cmd+j send_text all \n
map cmd+k send_text all \x0b
map cmd+l send_text all \x0c
map cmd+f send_text all \x06
map cmd+b send_text all \x02
