# Configuration for opening files when clicking on terminal hyperlinks.

# Open regular files in the editor.
protocol file
mime text/*
action launch --type=tab zsh -c '${EDITOR} ${FILE_PATH}'

# Open directories
protocol file
mime inode/directory
action launch --type=overlay-main --cwd $FILE_PATH
