notARepository: 'quit'
git:
  overrideGpg: true
  paging:
    colorArg: always
    pager: diff-so-fancy
os:
  editPreset: nvim
gui:
  showBottomLine: false
  theme:
    activeBorderColor:
      - magenta
    selectedLineBgColor:
      - black
    unstagedChangesColor:
      - yellow
  border: rounded
  nerdFontsVersion: '3'
keybinding:
  files:
    commitChangesWithoutHook: <disabled>
customCommands:
  - key: w
    prompts:
      - type: input
        title: Commit summary
        initialValue: ''
    description: Commit changes without pre-commit hook
    command: git commit -n -m "{{index .PromptResponses 0}}"
    context: files
