notARepository: 'quit'
git:
  overrideGpg: true
  paging:
    colorArg: always
    pager: diff-so-fancy
os:
  editPreset: nvim
gui:
  showBottomLine: false
  theme:
    activeBorderColor:
      - magenta
    selectedLineBgColor:
      - black
    unstagedChangesColor:
      - yellow
  border: rounded
  nerdFontsVersion: '3'
