# Window bindings:
bind = SUPER, A, fullscreen, 0
bind = SUPER, C, centerwindow
bind = SUPER, F, togglefloating
bind = SUPER, F, centerwindow
bind = SUPER, Q, killactive
bind = SUPER SHIFT, Q, exit

# System dashboard:
bind = SUPER, up, exec, ags -t dashboard

# Applications:
bind = SUPER, Space, exec, ags -t applauncher
bind = SUPER, T, exec, wezterm
bind = SUPER, B, exec, chromium

# Screenshots:
bind = SUPER SHIFT, S, exec, grim -g "$(slurp -c B08BBB -w 1 -b B08BBB80)"

# Audio:
bind = , XF86AudioMute, exec, ags -r 'audio.muted = !audio.muted; audio.emitChange()'
binde = , XF86AudioLowerVolume, exec, ags -r 'audio.volume -= 0.05; audio.emitChange()'
binde = , XF86AudioRaiseVolume, exec, ags -r 'audio.volume += 0.05; audio.emitChange()'

# Backlight:
binde = , XF86MonBrightnessDown, exec, ags -r 'backlight.brightness -= 0.05; backlight.emitChange()'
binde = , XF86MonBrightnessUp, exec, ags -r 'backlight.brightness += 0.05; backlight.emitChange()'

# Focus with SUPER + HJKL:
bind = SUPER, h, movefocus, l
bind = SUPER, l, movefocus, r
bind = SUPER, k, movefocus, u
bind = SUPER, j, movefocus, d

# Switch workspaces with SUPER + [0-5]:
bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5

# Move windows with SUPER + SHIFT + [0-5]:
bind = SUPER SHIFT, 1, movetoworkspace, 1
bind = SUPER SHIFT, 2, movetoworkspace, 2
bind = SUPER SHIFT, 3, movetoworkspace, 3
bind = SUPER SHIFT, 4, movetoworkspace, 4
bind = SUPER SHIFT, 5, movetoworkspace, 5
