source = ~/.config/hypr/bind.conf # Keybindings.
source = ~/.config/hypr/windowrule.conf # Window rules.

env = XCURSOR_SIZE,16 # Cursor size.

monitor=,highres,auto,2 # High resolution monitor.

# Execute on startup:
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # Update DBus environment.
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # Import stuff for XDPH.
exec-once = /usr/lib/polkit-kde-authentication-agent-1 # Authentication agent.
exec-once = swaybg -i ~/Pictures/Wallpapers/pixel-pink-cloudy-moon.png # Wallpaper.
exec-once = wl-paste --watch cliphist store # Clipboard.
exec-once = dunst # Notification daemon.

input {
    kb_layout = us
    touchpad {
        natural_scroll = true # macOS-like scrolling.
    }
}

# 3-finger swiping.
gestures {
    workspace_swipe = true
    workspace_swipe_distance = 200
}

general {
    gaps_in = 2 # Gaps between windows.
    gaps_out = 2 # Gaps between windows and monitors edges.
    border_size = 1 # Border size around windows.
    cursor_inactive_timeout = 5 # Hide cursor after 5 seconds of inactivity.
    resize_on_border = true # Resize windows by dragging their borders.
}

decoration {
    rounding = 5 # Window border radius.
    blur {
        enabled = false # I don't use this.
    }
}

# Smooth animations.
animations {
    enabled = yes
    bezier = easeOut, 0.2, 1, 0.2, 1
    animation = windows, 1, 5, easeOut
    animation = windowsIn, 1, 5, default, popin
    animation = workspaces, 1, 6, default
}

misc {
    disable_hyprland_logo = true # Disable the default anime background.
}

xwayland {
    force_zero_scaling = true # Avoid blurry XWayland apps.
}
