$BLACK = rgb(14, 20, 25)
$PURPLE = rgb(156, 99, 243)
$LAVENDER = rgb(208, 181, 243)

general {
    ignore_empty_input = true
}

# Enable fingerprint authentication.
auth {
    fingerprint {
        enabled = true
        present_message = (Scanning fingerprint...)
    }
}

# Dark solid background.
background {
    monitor =
    color = $BLACK
}

# Password input field.
input-field {
    fade_on_empty = false
    halign = center
    valign = center
    size = 800, 80
    placeholder_text =
    outline_thickness = 5
    inner_color = $LAVENDER
    outer_color = $PURPLE
}

# Input labels.
label {
    font_family = Cartograph CF Italic
    font_size = 18
    text = $FPRINTPROMPT
    halign = center
    valign = center
    position = 0, 80
    color = $LAVENDER
}

label {
    font_family = Cartograph CF Italic
    font_size = 48
    text = Unlock me
    halign = center
    valign = center
    position = 0, 140
    color = $LAVENDER
}
