# Floating windows:
windowrule = float, nwg-look
windowrulev2 = float, class:thunderbird, title:^Write

# Centered windows with specific sizes:
windowrulev2 = center, class:Chromium-browser, title:^_crx_ # Bitwarden vault login.
windowrulev2 = size 380 400, class:Chromium-browser, title:^_crx_
windowrulev2 = center, class:Chromium-browser, title:Open Files # Browser file picker.
windowrulev2 = size 900 500, class:Chromium-browser, title:Open Files
windowrulev2 = center, class:thunderbird, title:^Write # New email window.
windowrulev2 = size 60% 80%, class:thunderbird, title:^Write
windowrulev2 = center, class:Chromium-browser, title:^Element # Element client.
windowrulev2 = size 70% 80%, class:Chromium-browser, title:^Element # Element client.
