# Centering:
windowrule = center, wezterm.lf

# Floating windows:
windowrule = float, nwg-look
windowrule = float, org.kde.polkit-kde-authentication-agent-1
windowrule = float, wezterm.lf

# Sizing:
windowrule = size 900 600, wezterm.lf
