# Floating windows:
windowrule = float, nwg-look
windowrule = float, org.kde.polkit-kde-authentication-agent-1
windowrule = float, title:Bitwarden
windowrulev2 = float, class:thunderbird, title:^Write

# Centered windows:
windowrulev2 = center, class:thunderbird, title:^Write

# Size modifications:
windowrulev2 = size 60% 80%, class:thunderbird, title:^Write
