# Use the full display style
style = "full"

## Put the search bar at the top
invert = true

# Disable the moving list numbers
show_numeric_shortcuts = false

# Enable the daemon search which uses an in-memory index to perform fast and customizable searches
search_mode = "daemon-fuzzy"

# Don't store failed commands
store_failed = false

# Custom miss-dracula theme
[theme]
name = "miss-dracula"

## Enable and autostart the background daemon
[daemon]
enabled = true
autostart = true

[ui]
# Display order:
# - Directory where command was run
# - Absolute timestamp
# - Command
columns = [{ type = "directory", width = 30 }, "datetime", "command"]

[ai]
# Enable AI features.
enabled = true
