"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[manager]
preview_hovered = { underline = false }

[status]
separator_style = { fg = "darkgray", bg = "darkgray" }
mode_normal = { fg = "black", bg = "lightmagenta", bold = true }
mode_select = { fg = "black", bg = "lightgreen", bold = true }
mode_unset = { fg = "black", bg = "lightyellow", bold = true }
