"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = '[➜](bold green)'
error_symbol = "[!](bold red)"

[git_status]
disabled = true

[package]
disabled = true